export default [
  {
    title: "Git",
    url: "/assets/git.png",
    color: "#F4511E",
    width: "72px",
    height: "72px",
  },
  {
    title: "Css",
    url: "/assets/css.png",
    color: "#0277BD",
    width: "71px",
    height: "72px",
  },
  {
    title: "NodeJs",
    url: "/assets/node.png",
    color: "#21A366",
    width: "72px",
    height: "72px",
  },
  {
    title: "Flutter",
    url: "/assets/flutter.png",
    color: "#40C4FF",
    width: "71px",
    height: "72px",
  },
  {
    title: "GraphQL",
    url: "/assets/graphql.png",
    color: "#FF4081",
    width: "71px",
    height: "72px",
  },
  {
    title: "HTML",
    url: "/assets/html.png",
    color: "#E65100",
    width: "72px",
    height: "72px",
  },
  {
    title: "Javascript",
    url: "/assets/javascript.png",
    color: "#FFD600",
    width: "72px",
    height: "72px",
  },
  {
    title: "CI/CD",
    url: "/assets/ci-cd.png",
    color: "#ffffff",
    width: "86px",
    height: "41px",
  },
  {
    title: "React",
    url: "/assets/react.png",
    color: "#61DAFB",
    width: "72px",
    height: "62px",
  },
  {
    title: "Next",
    url: "/assets/nextjs.png",
    color: "#ffffff",
    width: "72px",
    height: "72px",
  },
  {
    title: "Python",
    url: "/assets/python.png",
    color: "#FFC107",
    width: "72px",
    height: "72px",
  },
  {
    title: "Typescript",
    url: "/assets/typescript2.png",
    color: "#1677C7",
    width: "56px",
    height: "56px",
  },
  {
    title: "Redux",
    url: "/assets/redux.png",
    color: "#7E57C2",
    width: "68px",
    height: "68px",
  },
  {
    title: "TailwindCss",
    url: "/assets/tailwind.png",
    color: "#ffffff",
    width: "68px",
    height: "42px",
  },
  {
    title: "Sass",
    url: "/assets/sass.png",
    color: "#F06292",
    width: "62px",
    height: "62px",
  },
  {
    title: "MongoDB",
    url: "/assets/mongo.png",
    color: "#ffffff",
    width: "33px",
    height: "72px",
  },
  {
    title: "AWS",
    url: "/assets/aws.png",
    color: "#ffffff",
    width: "70px",
    height: "44px",
  },
  {
    title: "Firebase",
    url: "/assets/firebase.png",
    color: "#FFCB2F",
    width: "48px",
    height: "60px",
  },
  {
    title: "Postgresql",
    url: "/assets/postgres.png",
    color: "#1677C7",
    width: "76px",
    height: "60px",
  },
  {
    title: "Rest Api",
    url: "/assets/api.png",
    color: "#ffffff",
    width: "74px",
    height: "74px",
  },
  {
    title: "Docker",
    url: "/assets/docker.png",
    color: "#2496ED",
    width: "88px",
    height: "52px",
  },
  {
    title: "Kubernets",
    url: "/assets/kubernets.png",
    color: "#326CE5",
    width: "70px",
    height: "68px",
  },
  {
    title: "C++",
    url: "/assets/cpp.png",
    color: "#0086D4",
    width: "71px",
    height: "72px",
  },
  {
    title: "Vercel",
    url: "/assets/vercel.png",
    color: "#ffffff",
    width: "52px",
    height: "52px",
  },
];
