import Head from "next/head";
import styles from "../styles/Home.module.scss";
import React from "react";
import { Footer, Header, Navbar, Projects, Skills } from "../containers";
import { NavigationDots, SocialsIcons } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Comet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {/* Fixed Social Icons */}
          <SocialsIcons />
        </div>
        <div>
          {/* Navigation Dots */}
          <NavigationDots />
        </div>
        <div
          className={`${styles.bgFrontGradient} grid grid-cols-12 px-gridPadding gap-x-gridGap`}
        >
          <div id="navbar" className="col-span-full">
            <Navbar />
          </div>
          <div id="header" className="min-h-screen col-span-full">
            <Header />
          </div>
        </div>
        <div className={`${styles.bgSecondGradient} px-gridPadding`}>
          <div id="skills" className="min-h-screen col-span-full">
            <Skills />
          </div>
          <div id="projects" className="min-h-screen col-span-full">
            <Projects />
          </div>
          <div id="footer" className="min-h-screen col-span-full">
            <Footer />
          </div>
        </div>
      </main>
    </div>
  );
}
